CREATE TABLE IF NOT EXISTS MenuItem (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS Order (
    id INT AUTO_INCREMENT PRIMARY KEY,
    orderDate DATETIME NOT NULL,
    totalPrice DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS OrderItem (
    id INT AUTO_INCREMENT PRIMARY KEY,
    orderId INT,
    menuItemId INT,
    quantity INT NOT NULL,
    FOREIGN KEY (orderId) REFERENCES Order(id),
    FOREIGN KEY (menuItemId) REFERENCES MenuItem(id)
);